### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by fedeisas** [rawaludin/laravel-notes#3]
I think you could move the "Search&Parse" stuff to a new class to keep the command cleaner and isolate the tests.

That class could take the $type and $path parameters.

I started fiddling with some code, but I saw you were planning on use git to lookup notes. I'm not sure how to use git for that. Can you give me some directions? I want to commit my PR with that change in place.

Thanks!

**Comment by fedeisas** [comment]
Reading all files on PHP is expensive. Can't we just pipe a `grep`?

Something like:

``` bash
$ grep -n -i -R -E "OPTIMIZE|TODO|FIXME" app/ --exclude-dir=storage
```

> -n Line Number
> -i case-insensitive
> -R recursive
> -E regular expression
> --exclude-dir exclusion pattern

``` php
$types = array('OPTIMIZE', 'TODO', 'FIXME');
$customTypes = array('foo'); // From command option, maybe comma separated

$pattern = implode('|', array_merge($customTypes, $types));
```

Then from PHP we could do something like:

``` php
exec('grep -n -i -R -E "OPTIMIZE|TODO" app/', $commandOutput);
// Have fun parsing $commandOutput to extract filename, line number, and description
```

**Comment by fedeisas** [comment]
@rahmatawaludin closing this.

**Comment by rawaludin** [comment]
My idea is to log all notes from current git status. So, for next notes commands run, it will only search in changed files.

**Comment by fedeisas** [comment]
Mmm, I'm not sure I understand the point. It's like you're working on a feature, start to drop todo's here and there, and before commiting you can check that your code is finished?

You could run something like `git status --sb` and pipe to grep to find those notes, I think.

**Comment by rawaludin** [comment]
I closed this feature, because there is no real gain using git to log notes.
